wandb_version: 1

lr:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704467041.447734
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.4
      5: 0.16.1
      8:
      - 5
      13: darwin-x86_64
