name: "Run tests on windows"

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]

jobs:
    test-windows:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Python 3.10.11
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.11
                  cache: "pip" # caching pip dependencies
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -e .
            - name: Test with pytest
              run: |
                  pytest -v
